#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.0/orangehrm-3.0.zip"
URL="http://sourceforge.net/projects/orangehrm/files/stable/$VERSION"

dl $URL /usr/local/src

