#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.3.3"
URL="http://download.sourceforge.net/project/orangehrm/stable/${VERSION}/orangehrm-${VERSION}.zip"

dl $URL /usr/local/src
