#!/bin/sh -ex

DB_NAME=orangehrm
DB_USER=orangehrm
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/orangehrm

# unpack and set required permissions
unzip $SRC/orangehrm-*.zip -d $(dirname $WEBROOT)
pdirname=$(ls $(dirname $WEBROOT) | grep orangehrm-)
rm $(dirname $WEBROOT)/orangehrm-*/orangehrm-quick-start-guide.html
mv $(dirname $WEBROOT)/orangehrm-*/orangehrm-* $WEBROOT
rm $(pdirname) -rf
rm $SRC/orangehrm-*.zip
sed -i "s|username_pk PRIMARY KEY (username))|username_pk PRIMARY KEY (username)) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC|" $WEBROOT/dbscript/dbscript-1.sql


chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/lib/logs
chown -R www-data:www-data $WEBROOT/lib/confs
chown -R www-data:www-data $WEBROOT/symfony/log
chown -R www-data:www-data $WEBROOT/symfony/cache
chown -R www-data:www-data $WEBROOT/symfony/config
chown -R www-data:www-data $WEBROOT/symfony/apps/orangehrm/config

# configure apache
a2dissite 000-default
a2ensite orangehrm
a2enmod rewrite

cat >> /etc/mysql/my.cnf <<EOF
[client]
default-character-set = utf8mb4
[mysqld]
innodb_file_format = Barracuda
innodb_file_per_table = 1
innodb_large_prefix
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
skip-character-set-client-handshake
[mysql]
default-character-set = utf8mb4
EOF

# start services
service mysql start
service apache2 start

# patch 1 line in sql file that causes installation issues
sed -i '/ohrm_oauth_user/ s/);/) ROW_FORMAT=dynamic;/' $WEBROOT/dbscript/dbscript-1.sql

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL_G="http://127.0.0.1/installer/installerUI.php"
URL_P="http://127.0.0.1/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=0&actionResponse=WELCOMEOK"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=1&actionResponse=LICENSEOK"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=2&actionResponse=DBINFO&cMethod=existing&dbHostName=127.0.0.1&dbHostPortModifier=port&dbHostPort=3306&dbName=$DB_NAME&dbOHRMUserName=$DB_USER&dbOHRMPassword=$DB_PASS&dbCreateMethod=existing"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=3&actionResponse=SYSCHECKOK"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=4&actionResponse=DEFUSERINFO&OHRMAdminUserName=$ADMIN_NAME&OHRMAdminPassword=$ADMIN_PASS&OHRMAdminPasswordConfirm=$ADMIN_PASS"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=5&actionResponse=CONFIRMED"
while $CURL $URL_G |grep pending; do
   sleep 2
   $CURL $URL_P
done

$CURL $URL_G
$CURL $URL_P --data "txtScreen=6&actionResponse=REGISTER"

$CURL $URL_G
$CURL $URL_P --data "txtScreen=7&actionResponse=NOREG&firstName=&userName=&company=&userEmail=&userTp=&userComments="

rm -f /tmp/cookie

# disable web based installer
cat >$WEBROOT/installer/.htaccess<<EOF
deny from all
EOF

# secure sensitive files
#chmod 640 $WEBROOT/lib/confs/Conf.php
#chmod 640 $WEBROOT/symfony/config/databases.yml
#chmod 640 $WEBROOT/symfony/apps/orangehrm/config/settings.yml

# tweak footer on login page
#CONF=$WEBROOT/symfony/apps/orangehrm/modules/auth/templates/loginSuccess.php
#sed -i "s|footer.*|footer'); ?>\n<div id='turnkey-credit' style='text-align:center;padding-top:20px;'><a href='https://www.turnkeylinux.org/orangehrm'>OrangeHRM Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></div>|" $CONF

# patch database to avoid potential row issue later
TABLES=$($MYSQL_BATCH --silent $DB_NAME --execute 'SHOW TABLES')
for TABLE in $TABLES; do
    $MYSQL_BATCH $DB_NAME --execute "ALTER TABLE $TABLE ROW_FORMAT=dynamic;"
done

# stop services
service mysql stop
service apache2 stop

