#!/bin/sh -ex

DB_NAME=orangehrm
DB_USER=orangehrm
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/orangehrm

# unpack and set required permissions
tar -zxf $SRC/orangehrm-*.tar.gz -C $(dirname $WEBROOT)
rm $(dirname $WEBROOT)/orangehrm-quick-start-guide.html
mv $(dirname $WEBROOT)/orangehrm-* $WEBROOT
rm $SRC/orangehrm-*.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/lib/logs
chown -R www-data:www-data $WEBROOT/lib/confs
chown -R www-data:www-data $WEBROOT/symfony/log
chown -R www-data:www-data $WEBROOT/symfony/cache
chown -R www-data:www-data $WEBROOT/symfony/config
chown -R www-data:www-data $WEBROOT/symfony/apps/orangehrm/config

# configure apache
a2dissite default
a2ensite orangehrm
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

