#!/bin/bash -ex

DB_NAME=orangehrm
DB_USER=orangehrm
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey12!

SRC=/usr/local/src
WEBROOT=/var/www/orangehrm

# unpack and set required permissions
unzip $SRC/orangehrm-*.zip -d $(dirname $WEBROOT)
rm $(dirname $WEBROOT)/orangehrm-quick-start-guide.html
mv $(dirname $WEBROOT)/orangehrm-* $WEBROOT
rm $SRC/orangehrm-*.zip


chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/lib/confs

# configure apache
a2dissite 000-default
a2ensite orangehrm
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

CONF=/var/www/orangehrm/installer/cli_install_config.yaml

sed -i "/databaseName/ s/:.*/: $DB_NAME/" $CONF
sed -i "/privilidgedDatabaseUser/ s/:.*/: $DB_USER/" $CONF
sed -i "/privilidgedDatabasePassword/ s/:.*/: $DB_PASS/" $CONF
sed -i "/isExistingDatabase/ s/:.*/: y/" $CONF

expect << EOF
spawn php /var/www/orangehrm/installer/console install:on-existing-database

expect "*License Agreement*\r"
expect " >"
send "yes\r"
expect "*Database Host Name*\r"
expect " >"
send "localhost\r"
expect "*Database Host Port*\r"
expect " >"
send "3306\r"
expect "*Database Name*\r"
expect " >"
send "orangehrm\r"
expect "*OrangeHRM Database Username*\r"
expect " >"
send "orangehrm\r"
expect "*OrangeHRM Database User Password*\r"
expect " >"
send "$DB_PASS\r"
expect " >"
send "\r"
expect "*Organization Name*\r"
expect " >"
send "TurnkeyLinux\r"
expect "*Country*\r"
expect " >"
send "united states\r"
expect "*Language*\r"
expect " >"
send "en_US\r"
expect "*Timezone Group*\r"
expect " >"
send "UTC\r"
expect " >"
send "UTC\r"
expect "*First Name*\r"
expect " >"
send "Admin\r"
expect "*Last Name*\r"
expect " >"
send "istrator\r"
expect "*Email*\r"
expect " >"
send "admin@example.com\r"
expect "*Contact Number*\r"
expect " >"
send "\r"
expect "*Admin Username*\r"
expect " >"
send "$ADMIN_NAME\r"
expect "*Password*\r"
expect " >"
send "$ADMIN_PASS\r"
expect "*Confirm Password*\r"
expect " >"
send "$ADMIN_PASS\r"
expect " >"
send "no\r"
expect " >"
send "yes\r"
set timeout 480
expect eof
EOF

# disable web based installer
cat >$WEBROOT/installer/.htaccess<<EOF
deny from all
EOF

# patch database to avoid potential row issue later
TABLES=$($MYSQL_BATCH --silent $DB_NAME --execute 'SHOW TABLES')
for TABLE in $TABLES; do
    $MYSQL_BATCH $DB_NAME --execute "ALTER TABLE $TABLE ROW_FORMAT=dynamic;"
done

# stop services
service mysql stop
service apache2 stop

