#!/bin/bash -e
# regenerate orangehrm secrets and mysql password

. /etc/default/inithooks

WEBROOT=/var/www/orangehrm

SECRET=$(mcookie)$(mcookie)
mysql -e "\
	UPDATE orangehrm.hs_hr_config
	SET value='$SECRET'
	WHERE name='csrf_secret';"

PASSWORD=$(head -c 32 /dev/random | base64)
mysql -e "\
	UPDATE orangehrm.hs_hr_config
	SET value='$PASSWORD'
	WHERE name='oauth.encryption_key';"
PASSWORD=$(head -c 32 /dev/random | base64)
mysql -e "\
	UPDATE orangehrm.hs_hr_config
	SET value='$PASSWORD'
	WHERE name='oauth.token_encryption_key';"

PASSWORD=$(mcookie)
CONF=$WEBROOT/lib/confs/Conf.php
sed -i "s|->dbPass *=.*|->dbPass = '$PASSWORD';|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=orangehrm --pass="$PASSWORD"

