#!/bin/bash -e
# regenerate orangehrm secrets and mysql password

. /etc/default/inithooks

WEBROOT=/var/www/orangehrm

SECRET=$(mcookie)
CONF=$WEBROOT/symfony/apps/orangehrm/config/settings.yml
sed -i "s|crsf_secret.*|crsf_secret: '$SECRET'|" $CONF

PASSWORD=$(mcookie)
CONF=$WEBROOT/lib/confs/Conf.php
sed -i "s|dbpass.*|dbpass = '$PASSWORD';|" $CONF

CONF=$WEBROOT/symfony/config/databases.yml
sed -i "s|password.*|password: $PASSWORD|g" $CONF

CONF=$WEBROOT/symfony/cache/orangehrm/prod/config/config_databases.yml.php
if [ -e $CONF ]; then
    sed -i "s|password.*|password' => '$PASSWORD',|" $CONF
fi

$INITHOOKS_PATH/bin/mysqlconf.py --user=orangehrm --pass="$PASSWORD"

